# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class UserRole(StrEnum):
    USER = 'USER'
    ADMIN = 'ADMIN'

class LeadSource(StrEnum):
    FACEBOOK_COMMENT = 'FACEBOOK_COMMENT'
    FACEBOOK_LIKE = 'FACEBOOK_LIKE'
    FACEBOOK_MESSAGE = 'FACEBOOK_MESSAGE'
    FACEBOOK_LEAD_AD = 'FACEBOOK_LEAD_AD'
    WEB_FORM = 'WEB_FORM'
    WHATSAPP = 'WHATSAPP'
    MANUAL = 'MANUAL'

class LeadStatus(StrEnum):
    NEW = 'NEW'
    CONTACTED = 'CONTACTED'
    QUALIFIED = 'QUALIFIED'
    CONVERTED = 'CONVERTED'
    UNSUBSCRIBED = 'UNSUBSCRIBED'

class ConsentType(StrEnum):
    EXPLICIT_OPTIN = 'EXPLICIT_OPTIN'
    FACEBOOK_MESSAGE = 'FACEBOOK_MESSAGE'
    WEB_FORM_SUBMISSION = 'WEB_FORM_SUBMISSION'
    LEAD_AD_SUBMISSION = 'LEAD_AD_SUBMISSION'

class MessageType(StrEnum):
    TEXT = 'TEXT'
    TEMPLATE = 'TEMPLATE'
    MEDIA = 'MEDIA'

class MessagePlatform(StrEnum):
    WHATSAPP = 'WHATSAPP'
    MESSENGER = 'MESSENGER'

class MessageStatus(StrEnum):
    PENDING = 'PENDING'
    SENT = 'SENT'
    DELIVERED = 'DELIVERED'
    READ = 'READ'
    FAILED = 'FAILED'

class CampaignType(StrEnum):
    WHATSAPP_TEMPLATE = 'WHATSAPP_TEMPLATE'
    MESSENGER_BROADCAST = 'MESSENGER_BROADCAST'
    FOLLOW_UP = 'FOLLOW_UP'

class CampaignStatus(StrEnum):
    DRAFT = 'DRAFT'
    SCHEDULED = 'SCHEDULED'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    PAUSED = 'PAUSED'
    CANCELLED = 'CANCELLED'

