from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'FacebookPage',
    'FacebookPost',
    'WhatsappNumber',
    'WhatsappTemplate',
    'Lead',
    'Tag',
    'LeadTag',
    'Message',
    'Campaign',
    'AuditLog',
    'ApiKey',
    'RateLimit',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'facebookPages': 'FacebookPage',
        'whatsappNumbers': 'WhatsappNumber',
        'leads': 'Lead',
        'campaigns': 'Campaign',
        'auditLogs': 'AuditLog',
    },
    'FacebookPage': {
        'user': 'User',
        'posts': 'FacebookPost',
        'leads': 'Lead',
    },
    'FacebookPost': {
        'facebookPage': 'FacebookPage',
    },
    'WhatsappNumber': {
        'user': 'User',
        'templates': 'WhatsappTemplate',
        'messages': 'Message',
    },
    'WhatsappTemplate': {
        'whatsappNumber': 'WhatsappNumber',
        'messages': 'Message',
    },
    'Lead': {
        'user': 'User',
        'facebookPage': 'FacebookPage',
        'tags': 'LeadTag',
        'messages': 'Message',
    },
    'Tag': {
        'leads': 'LeadTag',
    },
    'LeadTag': {
        'lead': 'Lead',
        'tag': 'Tag',
    },
    'Message': {
        'lead': 'Lead',
        'campaign': 'Campaign',
        'whatsappNumber': 'WhatsappNumber',
        'whatsappTemplate': 'WhatsappTemplate',
    },
    'Campaign': {
        'user': 'User',
        'messages': 'Message',
    },
    'AuditLog': {
        'user': 'User',
    },
    'ApiKey': {
    },
    'RateLimit': {
    },
}

# fmt: on